name: Continuos Integration and Delivery with GitHub Actions
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: SetUp Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build Application .jar
        working-directory: ./project
        run: mvn clean package

      - name: Docker Compose Buildr
        working-directory: ./
        run: docker compose -f docker-compose.build.yml build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/minhareceita:latest ${{ secrets.DOCKER_USERNAME }}/minhareceita:${{ github.run_id }}
        
          docker push ${{ secrets.DOCKER_USERNAME }}/minhareceita:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/minhareceita:${{ github.run_id }}